### ISSUE TITLE
Web Controller - Websocket AssertionError

### ISSUE THREAD

**Issue by wallarug** [autorope/donkeycar#634]
When you are driving in the simulator.  This is on Ubuntu.  It is a very intermittent issue.

![image](https://user-images.githubusercontent.com/11770912/93750568-05e11e00-fc3f-11ea-8056-13ea750a6ff1.png)

Students have been able to replicated it across a few different systems.

**Comment by wallarug** [comment]
Hey is this resolved now? @sctse999

**Comment by calumsbaird** [comment]
I'm still receiving this identical error on ubuntu at random intervals, working from the latest version on dev branch

**Comment by sctse999** [comment]
this has been fixed on master branch. I didn't have time to port it back to dev branch yet. If you have time, could you please do it? you can refer to this PR.

https://github.com/autorope/donkeycar/pull/646

**Comment by wallarug** [comment]
That's Jonathan for the heads up - that is something I can look at doing once I finish my work for tonight.  No worries 👍
